-- MySQL Script generated by MySQL Workbench
-- Mon Feb 18 11:50:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alarm_gateway
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alarm_gateway` ;

-- -----------------------------------------------------
-- Schema alarm_gateway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alarm_gateway` DEFAULT CHARACTER SET latin1 ;
USE `alarm_gateway` ;

-- -----------------------------------------------------
-- Table `alarm_gateway`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alarm_gateway`.`locations` ;

CREATE TABLE IF NOT EXISTS `alarm_gateway`.`locations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `postal_code` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `street_number` VARCHAR(255) NULL DEFAULT NULL,
  `town` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `alarm_gateway`.`alarm_gateway`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alarm_gateway`.`alarm_gateway` ;

CREATE TABLE IF NOT EXISTS `alarm_gateway`.`alarm_gateway` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `MAC` VARCHAR(45) NULL DEFAULT NULL,
  `settings_profile` INT(11) NULL DEFAULT NULL,
  `location_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_gateway_location_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `FKb7hoc6kksg74s3egglviymfow`
    FOREIGN KEY (`location_id`)
    REFERENCES `alarm_gateway`.`locations` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `alarm_gateway`.`labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alarm_gateway`.`labels` ;

CREATE TABLE IF NOT EXISTS `alarm_gateway`.`labels` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `alarm_gateway`.`location_label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alarm_gateway`.`location_label` ;

CREATE TABLE IF NOT EXISTS `alarm_gateway`.`location_label` (
  `location_id` INT(11) NOT NULL,
  `label_id` INT(11) NOT NULL,
  INDEX `FKlgsmgj4xm9nafdbt7x2mbwkfi` (`label_id` ASC) VISIBLE,
  INDEX `FKr59dotp1e0ygbhkymo6hyxx7p` (`location_id` ASC) VISIBLE,
  CONSTRAINT `FKlgsmgj4xm9nafdbt7x2mbwkfi`
    FOREIGN KEY (`label_id`)
    REFERENCES `alarm_gateway`.`labels` (`id`),
  CONSTRAINT `FKr59dotp1e0ygbhkymo6hyxx7p`
    FOREIGN KEY (`location_id`)
    REFERENCES `alarm_gateway`.`locations` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
